// <auto-generated />
namespace PRSWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddedListGetAddChangeandRemovetoUsersController : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedListGetAddChangeandRemovetoUsersController));
        
        string IMigrationMetadata.Id
        {
            get { return "201710031601372_Added List(), Get(), Add(), Change() and Remove() to UsersController"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
